// Generated by CoffeeScript 1.7.1
(function() {
  var numberWriter, primeWriter, primesGenerator;

  if (typeof require !== "undefined" && require !== null) {
    primesGenerator = primesGenerator || require('./primes-generator');
    numberWriter = numberWriter || require('./number-writer');
  }

  primeWriter = (function(primesGenerator, numberWriter) {
    var myLib, yieldFirstPrimesWords;
    yieldFirstPrimesWords = function(generateTo, onYieldCallback) {
      var prime, primeWords, primes, _i, _len;
      primes = primesGenerator.generateFirst(generateTo);
      console.log(primes.length);
      console.log(primes);
      for (_i = 0, _len = primes.length; _i < _len; _i++) {
        prime = primes[_i];
        primeWords = numberWriter.write(prime);
        onYieldCallback.call(this, prime, primeWords);
      }
      return 1;
    };
    myLib = {
      yieldFirstPrimesWords: yieldFirstPrimesWords
    };
    if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
      module.exports = myLib;
    }
    return myLib;
  })(primesGenerator, numberWriter);

}).call(this);
